/**
 * Generates responsive image variants from the committed sources.
 *
 * Source precedence, per image id:
 *   1. media/originals/<id>.<ext>  - high-res, added later. Wins when present.
 *   2. media/web/<id>.<ext>        - 1920px versions scraped from the old Super site.
 *
 * Output (both gitignored, regenerated by `npm run images`):
 *   static/images/<id>-<width>.{avif,webp,jpg|png}
 *   src/lib/data/photo-sizes.json  - intrinsic dimensions + which variants exist
 *
 * Dropping originals in and re-running is the whole upgrade path. No markup changes.
 */
import { mkdir, readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ORIGINALS = path.join(ROOT, 'media', 'originals');
const WEB = path.join(ROOT, 'media', 'web');
const OUT = path.join(ROOT, 'static', 'images');
const SIZES_JSON = path.join(ROOT, 'src', 'lib', 'data', 'photo-sizes.json');

const WIDTHS = [640, 1280, 1920];
const CONCURRENCY = 4;

const photos = JSON.parse(await readFile(path.join(ROOT, 'src/lib/data/photos.json'), 'utf8'));

/** Map id -> source file, preferring media/originals. */
async function resolveSources() {
	const index = new Map();
	for (const dir of [WEB, ORIGINALS]) {
		if (!existsSync(dir)) continue;
		for (const file of await readdir(dir)) {
			if (!/\.(jpe?g|png|webp|tiff?|avif)$/i.test(file)) continue;
			const id = file.replace(/\.[^.]+$/, '');
			// ORIGINALS is walked second, so it overwrites WEB.
			index.set(id, path.join(dir, file));
		}
	}
	return index;
}

async function newerThan(src, out) {
	if (!existsSync(out)) return true;
	const [a, b] = await Promise.all([stat(src), stat(out)]);
	return a.mtimeMs > b.mtimeMs;
}

async function processOne(id, srcPath, fromOriginals) {
	const image = sharp(srcPath, { failOn: 'none' });
	const meta = await image.metadata();
	const isPng = meta.format === 'png';
	const fallbackExt = isPng ? 'png' : 'jpg';

	const widths = WIDTHS.filter((w) => w <= meta.width);
	if (widths.length === 0) widths.push(meta.width);

	for (const w of widths) {
		const jobs = [
			[`${id}-${w}.avif`, (p) => p.avif({ quality: 52, effort: 3 })],
			[`${id}-${w}.webp`, (p) => p.webp({ quality: 80 })],
			[
				`${id}-${w}.${fallbackExt}`,
				(p) => (isPng ? p.png({ compressionLevel: 9, palette: true }) : p.jpeg({ quality: 82, mozjpeg: true }))
			]
		];
		for (const [name, encode] of jobs) {
			const dest = path.join(OUT, name);
			if (!(await newerThan(srcPath, dest))) continue;
			await encode(sharp(srcPath, { failOn: 'none' }).resize({ width: w, withoutEnlargement: true })).toFile(dest);
		}
	}

	return {
		id,
		width: meta.width,
		height: meta.height,
		widths,
		ext: fallbackExt,
		source: fromOriginals ? 'originals' : 'web'
	};
}

async function main() {
	await mkdir(OUT, { recursive: true });
	const sources = await resolveSources();

	const ids = Object.keys(photos);
	const missing = ids.filter((id) => !sources.has(id));
	if (missing.length) {
		console.warn(`! no source file for ${missing.length} id(s): ${missing.slice(0, 5).join(', ')}`);
	}

	const todo = ids.filter((id) => sources.has(id));
	const results = {};
	let done = 0;

	async function worker() {
		while (todo.length) {
			const id = todo.shift();
			const srcPath = sources.get(id);
			const fromOriginals = srcPath.startsWith(ORIGINALS);
			results[id] = await processOne(id, srcPath, fromOriginals);
			done++;
			if (done % 10 === 0 || done === ids.length) {
				process.stdout.write(`  ${done}/${ids.length}\r`);
			}
		}
	}
	await Promise.all(Array.from({ length: CONCURRENCY }, worker));

	const sorted = Object.fromEntries(Object.keys(results).sort().map((k) => [k, results[k]]));
	await writeFile(SIZES_JSON, JSON.stringify(sorted, null, 2) + '\n');

	const fromOriginals = Object.values(results).filter((r) => r.source === 'originals').length;
	console.log(
		`\nimages: ${Object.keys(results).length} processed ` +
			`(${fromOriginals} from media/originals, ${Object.keys(results).length - fromOriginals} from media/web)`
	);
}

await main();
